"""add ai analysis fields

Revision ID: 2440e680dd43
Revises: b669dc2cf1c5
Create Date: 2026-05-25 13:55:17.106297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2440e680dd43'
down_revision: Union[str, None] = 'b669dc2cf1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('action_items', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('decisions', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'analyzed_at')
    op.drop_column('meetings', 'decisions')
    op.drop_column('meetings', 'action_items')
    op.drop_column('meetings', 'summary')
    # ### end Alembic commands ###
